export default {
    back: require('../assets/back.png'),
    cart: require('../assets/cart.png'),
    sort: require('../assets/sort.png'),
    popular: require('../assets/popular.png'),
    star: require('../assets/star.png'),
    heart: require('../assets/heart.png'),
    love: require('../assets/love.png'),
    user: require('../assets/user.png'),
    search: require('../assets/search.png'),
    category: require('../assets/category.png'),
    category_fill: require('../assets/category-fill.png'),
    home: require('../assets/home.png'),
    basket: require('../assets/basket.png'),
    minus: require('../assets/minus.png'),
    plus: require('../assets/plus.png'),
    bin: require('../assets/bin.png'),
    addToCart: require('../assets/add-to-cart.png'),
    sizeM: require('../assets/sizeM.png'),
    sizeL: require('../assets/sizeL.png'),
    account: require('../assets/account.png'),
    logout: require('../assets/log-out.png'),
    orderHistory: require('../assets/order-history.png'),
    edit: require('../assets/edit.png'),
    favourite_active: require('../assets/favourite-active.png'),
    favourite_unactive: require('../assets/favourite-unactive.png'),


    drink: require('../assets/drink.png'),
    hotCoffee: require('../assets/hot-coffee.png'),
    iceCoffee: require('../assets/ice-coffee.png'),
    iceCream: require('../assets/ice-cream.png'),
    dessert: require('../assets/dessert.png'),
    blendedIce: require('../assets/blended-ice.png'),
    email :require('../assets/3.png'),
    pass: require('../assets/2.png'),
    gg: require('../assets/gg.png'),

}